### ISSUE TITLE
Plugins over a real network

### ISSUE THREAD

**Issue by vinglogn** [hashicorp/go-plugin#124]
I think the net-based RPC plugin mechanism is very useful, do you have a support plan?

**Comment by mitchellh** [comment]
This is not planned. A perfectly reliable network is a requirement of this system (effectively only loopback devices). Introducing unreliability in the network creates a number of failure scenarios that this framework is not well equipped to handle. Additionally, by having a reliable network the end application and plugins simpler because they can be very confident the communication is received. 

We don’t currently plan on supporting the failure scenarios introduced by remote plugins.
