### ISSUE TITLE
reliable performance

### ISSUE THREAD

**Issue by overtalk** [hashicorp/go-plugin#132]
I know the advantage of this repo, such as dynamic & process isolation, but how about the benchmark? any test data?

**Comment by mitchellh** [comment]
We don't have any benchmarks. In real world usage across our products we haven't had any real performance issues from this and go-plugin is used in some serious scale environments with Vault, Nomad. Products like Packer exercise go-plugin very differently: large multi-gigabyte files are often transmitted over the connection, but it isn't high request/sec. 

So, our lack of benchmarks is mostly because we haven't needed to benchmark it since over 6 or 7 years (since before it was extracted) we haven't had any real issues.
