### ISSUE TITLE
plugin talk to host

### ISSUE THREAD

**Issue by genecyber** [hashicorp/go-plugin#15]
I was able to split the basic example into 2 binaries, I can get the response back to my host from the plugin, but I can't understand how the plugin can call into the host.

**Comment by mitchellh** [comment]
We do this in some of our projects. 

You create a call to the plugin that sends the address of a listening RPC server on the host. The plugin then connects to the host and calls it like a normal RPC server. 

In our implementation the host only listens for one connection. Once that connection is made we establish the RPC conn and close the listener so that no further connections can be made.

**Comment by mjstich** [comment]
Can you give a pointer to the code in the other projects which implements the plugin initiating communications with the host?
