### ISSUE TITLE
Vendored interface types

### ISSUE THREAD

**Issue by zmb3** [hashicorp/go-plugin#16]
I have a plugin that wants to use types defined in the host application.  The plugin vendors the code from the host application.  I'm getting an error at runtime:

> reading body gob: name not registered for interface "github.com/me/plugin/vendor/github.com/me/hostapp/plugins.MyInterface"

I am calling `gob.Register` for the types that implement the interface, but since I'm vendoring they get registered under a different type name and the gob decoding fails.

Are you aware of any projects that have used `go-plugin` in this manner?  I know I can either:
- stop vendoring and build against code in my GOPATH, or
- only use concrete types between the host/plugins instead of interfaces

I just wanted to check to see if others have run into this came up with a different solution.

**Comment by mitchellh** [comment]
This is a couple years old and I'm sorry for that. We've used vendoring across our projects for years, and this includes the interfaces that plugins implement, and we've never seen this issue. I'm going to close this since its been awhile but just let me know if this is still happening! Go modules might have changed this, too.
