### ISSUE TITLE
stdout is polluted before handshake

### ISSUE THREAD

**Issue by vitrun** [hashicorp/go-plugin#164]
Hi, 
Go-plugin relies on stdout to handshake, however, stdout is likely to be polluted by other modules inited before go-plugin. For example, in module A：

```go
func init() {
fmt.Println("Hey, this happens before init of go-plugin")
}
``` 

As for handshake, do we have alternatives to stdout?

**Comment by mitchellh** [comment]
I would challenge it isn't "likely to be polluted" since we've used go-plugin in a number of projects with hundreds of transitive Go dependency and have never once had an issue. I'd argue its fairly hostile for anything to output to stdout in an init function. 😄 

There are no plans currently to use anything other than stdout for the [handshake](https://github.com/hashicorp/go-plugin/blob/0c19a1387af146eaa3335dad0a021741344ac3e9/docs/internals.md#handshake). There have been requests to enable some functionality of redirecting stdout _after_ the handshake but so far we've been against that as well (to just keep it flexible for how we modify the handshake in the future). 

I'd recommend if you need non-stdout support that you fork the project for your needs.
