### ISSUE TITLE
Can we  version this project?

### ISSUE THREAD

**Issue by dantran** [hashicorp/go-plugin#30]
This way i can lock Go app from changes at this module

**Comment by mitchellh** [comment]
We prefer not to if possible... please allow me to explain why.

First, vendoring has now become the official approach taken by Go. We recommend vendoring as a way to lock libraries. All major vendoring tools today support locking at a ref.

Second, we ourselves don't version our projects. So historically when we have tagged "releases", our projects often simply _never_ update the version until someone comes along and says "hey, can you cut a release?" And sometimes its been a very long time.

We have "versioned" via tagging before in a couple cases. First, we did so prior to vendoring becoming an official stance. And second, we did so to support some Linux distributions that require a tag to build (although its quite a bad way of locking a Go dependency for reasons above, we've forgotten to update a tag for security fixes before just because we forget we tagged any projects). This latter case seems to have dropped off recently though.

So, if you really need a tag or to lock the project, I recommend just locking it to the master ref. We try to keep master stable, although we generally don't hold back anymore on backwards incompatibilities of libraries since we assume everyone is vendoring at this point. 

Sorry, its just not something we currently do for Go libraries.

**Comment by dantran** [comment]
Thanks for the detail explanation,  i will find a way to lock down at a mater ref via our tooling ( mvn-golang)
