### ISSUE TITLE
Handling plugin crashes

### ISSUE THREAD

**Issue by paul-argeniss** [hashicorp/go-plugin#31]
Hello. I would like to know what is the recommended way of handling plugin crashes (i.e. the plugin process shutting down). I noticed go-plugin doesn't restart the process in this situation, so I was wondering if you are considering adding this feature, and if you are not then I would like to know the rationale behind that decision. Initially my idea was to verify the plugin status before any call, and start it if the process is down, but I wanted to check with you guys first in case I'm missing something. Thanks!

**Comment by mitchellh** [comment]
Hey @paul-argeniss! We utilize the `Ping` method for this: https://github.com/hashicorp/go-plugin/blob/5ee1a665d1862b865bd2203cdce4f08e39841815/rpc_client.go#L167 Method calls in general will also start failing with errors.

So we usually take one of two approaches:

1.) Design our calls that are going to go over a plugin to expect an error can happen at any time (due to a plugin crashing) and handle that accordingly. This may involve creating a new client and relaunching the process.

2.) Call Ping() out of band at opportune times to determine if we need to restart a plugin.

It could be interesting to build in a restart mechanism into the Client itself, but existing plugin connections are going to be invalid going forward in any case.
