### ISSUE TITLE
Consider Apache License?

### ISSUE THREAD

**Issue by mastersingh24** [hashicorp/go-plugin#36]
Would you ever consider moving to an Apache license and/or dual licensing?

**Comment by jefferai** [comment]
Can you describe why the MPL is not sufficient for your needs?

**Comment by mitchellh** [comment]
I'm also interested in knowing your needs for Apache licensing.

I'll note that as a company that primarily sells OSS software or closed source software built on top of OSS software, we've of course spent many hours with lawyers (from multiple firms, too) on OSS licensing. I don't want to get into the details of those meetings since in a single quickly typed comment I won't properly (legally) explain the various reasons, but the conclusion of those meetings corroborated by the multiple firms was that MPL2 was a good option for us. 

I'll note that other license types were also "good options" for a variety of reasons. So I'm not saying Apache is bad, it is just that for us MPL2 was concluded as a good choice for our business.

Given the above, we're unlikely to adopt another licensing model. However, please share your reasons since it is helpful for our understanding and it may be able to sway our opinions.

**Comment by mastersingh24** [comment]
First, sorry for the short question without any supporting details and second thanks for the prompt response.

The main project I'm working on is released under the Apache license.  As with many Golang projects, we vendor our dependencies and we actually currently maintain the vendor folder in our repository.  Of course there are a mix of licenses across our dependencies.  And while we don't currently have an issue (we are allowed to use most "copyleft" license types) it would be more *convenient* for us if we used Apache licensed dependencies.

I posted the question here because we don't currently use the go-plugin package but we are considering it.  For now, the MPL2 license will not inhibit our ability to use it and perhaps as the Go community improves dependency / package mgmt we won't need to store the vendor folder in our source tree at all
