### ISSUE TITLE
host and plugin on different machines?

### ISSUE THREAD

**Issue by cyrilleverrier** [hashicorp/go-plugin#64]
Could you please clarify for me if  `go-plugin` can be use in a way that the host application and the plugins are on different machines?
Since it uses `gRPC` or `net/rpc`, I would expect that it should be doable.
But the `net/rpc` connection is forced to use `unix` or `127.0.0.1` on Windows machine

**Comment by mitchellh** [comment]
I'm sure it'll "work" but one of the underlying assumptions made is that the underlying network connection is reliable. The only way to ensure this generally is a loopback connection. It may work though if all methods of your interface return errors and every call is checked for errors.

go-plugin won't retry or reconnect automatically in any case so you'll probably have to be diligent around that too. Both aren't necessary on loopback because the connection is generally guaranteed by the OS to never be cut unless the process dies on either side.
