### ISSUE TITLE
'go-getter' integration

### ISSUE THREAD

**Issue by uded** [hashicorp/go-plugin#70]
I see it on the roadmap, but no other mention. Any chance for this to see daylight?

**Comment by ghostsquad** [comment]
Bump. Sorry if this is an inappropriate way to get attention here. I'm just starting to do some research on implementing a cli tool that uses plugins, and I was hoping this repo would be the solution. I'm concerned that of the few issues open, they are quite old and without updates.

**Comment by mitchellh** [comment]
We don't have any current plans to continue with this roadmap item. Our tooling has individually implemented plugin downloading in different ways. We last discussed this a couple years ago and didn't see a useful integration here that would go beyond doing something you could do pretty easily yourself. If you have any ideas we're open to it. I'm going to close this now and remove that from the roadmap unless otherwise convinced!

**Comment by ghostsquad** [comment]
@mitchellh sounds good. I was mostly interested in some sort of "standard" way, like terraform to download a binary that (the plugin) based on version constraints. (https://www.terraform.io/docs/configuration/providers.html)

This type of feature definitely feels orthogonal to this project. Do you by chance know of a library that makes this functionality easy to implement?

**Comment by mitchellh** [comment]
I can share with you the way _we_ strung those together. We use go-getter, go-plugin, and [go-version](https://github.com/hashicorp/go-version). We built our own "protocol" that tells us the version in the HTTP headers (we used to just use filename but now we send more information down via headers) so that we don't download things we don't need.
